[default]
extend-ignore-identifiers-re = ["wrk", "flate", "ND", "typ", "ful"]

[default.extend-identifiers]
# typos in third-party code/libraries
WrittingCSV = "WrittingCSV"
seperator   = "seperator"

[default.extend-words]
# these are false positives in data/examples
ALLE          = "ALLE"
ba            = "ba"
Environnement = "Environnement"
fo            = "fo"
hel           = "hel"
inout         = "inout"
UE            = "UE"
seeked        = "seeked"
DNE           = "DNE"
Generice      = "Generice"
Portugese     = "Portugese"

[files]
extend-exclude = [
    "*.csv",
    "*.geojson",
    "*.ipynb",
    "*.jsonl",
    "*.lua",
    "*.pynb",
    "*.ssv",
    "*.tab",
    "nyc311-describegpt*.*",
    "docs/describegpt/*",
]
