[package]
name = "qsv-clap-completions"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["string"] }
clap_complete = "4.5.8"
clap_complete_fig = "4.5.1"
clap_complete_nushell = "4.5.2"
qsv_docopt = "1.9"
